[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"
access-control-allow-origin="*"

[logging]
filename="logs/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[ "10.254.20.10:2181", "10.254.20.11:2181", "10.254.20.12:2181" ]
timeout=6
root-path="/burrow"

[client-profile.test]
client-id="burrow-test"
kafka-version="0.10.0"
tls="tlsprofile"
sasl="saslprofile"

[tls.tlsprofile]
certfile="https://kafka-service-broker.cf.sap.hana.ondemand.com/certs/rootCA.crt"
keyfile="https://kafka-service-oauth.cf.sap.hana.ondemand.com/v1/token_key"
#cafile="https://kafka-service-oauth.cf.sap.hana.ondemand.com/v1/39976793-dd2d-411a-bdf8-5504188dd84b/token"
noverify=false

[sasl.saslprofile]
username="sbss_y_q4kldjgdvbp-ci3xq9ybt7qx4eodjj5ie3kug_yettkouo26be0aavg10orltz_i0="
password="aa_l9X8Rj4vDh+Fggsv8K9z54Wbx24="
handshake-first=false

[cluster.local]
class-name="kafka"
servers=[ "10.254.20.21:9093", "10.254.20.22:9093", "10.254.20.23:9093" ]
client-profile="test"
topic-refresh=120
offset-refresh=30

[consumer.local]
class-name="kafka"
cluster="local"
servers=[ "10.254.20.21:9093", "10.254.20.22:9093", "10.254.20.23:9093" ]
client-profile="test"
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[httpserver.default]
address=":8000"

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1

